-- Track 2 / Phase 1A crypto-pair event sink contract
-- Optional persistence target for future ClickHouse + Grafana wiring.
-- JSONL artifacts remain the default source of truth until the sink is
-- explicitly enabled by a later packet.

CREATE TABLE IF NOT EXISTS polytool.crypto_pair_events
(
    event_id String,
    event_type LowCardinality(String),
    schema_version LowCardinality(String),
    event_ts DateTime64(3, 'UTC'),
    recorded_at DateTime64(3, 'UTC'),
    run_id String,
    mode LowCardinality(String),
    source LowCardinality(String),
    market_id String,
    condition_id String,
    slug String,
    symbol LowCardinality(String),
    duration_min UInt16,
    opportunity_id String,
    intent_id String,
    fill_id String,
    settlement_id String,
    transition_id String,
    leg LowCardinality(String),
    token_id String,
    side LowCardinality(String),
    state_key LowCardinality(String),
    from_state String,
    to_state String,
    reason String,
    exposure_status LowCardinality(String),
    winning_leg LowCardinality(String),
    yes_token_id String,
    no_token_id String,
    yes_quote_price Nullable(Float64),
    no_quote_price Nullable(Float64),
    pair_quote_cost Nullable(Float64),
    target_pair_cost_threshold Nullable(Float64),
    threshold_edge_usdc Nullable(Float64),
    pair_size Nullable(Float64),
    intended_yes_price Nullable(Float64),
    intended_no_price Nullable(Float64),
    intended_pair_cost Nullable(Float64),
    intended_paired_notional_usdc Nullable(Float64),
    fill_price Nullable(Float64),
    fill_size Nullable(Float64),
    fill_notional_usdc Nullable(Float64),
    fee_adjustment_usdc Nullable(Float64),
    net_cash_delta_usdc Nullable(Float64),
    paired_size Nullable(Float64),
    paired_cost_usdc Nullable(Float64),
    paired_fee_adjustment_usdc Nullable(Float64),
    paired_net_cash_outflow_usdc Nullable(Float64),
    unpaired_size Nullable(Float64),
    unpaired_notional_usdc Nullable(Float64),
    unpaired_max_loss_usdc Nullable(Float64),
    unpaired_max_gain_usdc Nullable(Float64),
    settlement_value_usdc Nullable(Float64),
    gross_pnl_usdc Nullable(Float64),
    net_pnl_usdc Nullable(Float64),
    markets_seen Nullable(UInt32),
    opportunities_observed Nullable(UInt32),
    threshold_pass_count Nullable(UInt32),
    threshold_miss_count Nullable(UInt32),
    order_intents_generated Nullable(UInt32),
    paired_exposure_count Nullable(UInt32),
    partial_exposure_count Nullable(UInt32),
    settled_pair_count Nullable(UInt32),
    open_unpaired_notional_usdc Nullable(Float64),
    quote_age_seconds Nullable(UInt32),
    threshold_passed Nullable(Bool),
    assumptions_json String,
    event_payload_json String
)
ENGINE = ReplacingMergeTree(recorded_at)
ORDER BY (run_id, event_type, event_ts, event_id)
SETTINGS index_granularity = 8192;

GRANT SELECT ON polytool.crypto_pair_events TO grafana_ro;
